version: "3"
services:
  web:
    image: tarrsalah/php-apache
    ports:
      - 3000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    links:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 3300:8080
    depends_on:
      - mariadb
    links:
      - mariadb
volumes:
  mariadb_volume:
